name: Liberation

on:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  call-liberation-workflow:
    uses: cedeirasf/CedMT-devops-workflows/.github/workflows/liberation.yml@v1
    secrets:
      github-token: ${{ secrets.GH_PROJECT_AUTOMATION }}
