name: Project Automations

on:
  issues:
    types: 
      - opened
      - closed
      - assigned
  pull_request:
    types: 
      - opened

permissions:
  repository-projects: write

jobs:
  call-project-automation-workflow:
    uses: cedeirasf/CedMT-devops-workflows/.github/workflows/project-automation.yml@v1
    secrets:
      GH_PROJECT_AUTOMATION: ${{ secrets.GH_PROJECT_AUTOMATION }}
